/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_ruanyandong_androidndk_HelloWorld */

#ifndef _Included_com_ruanyandong_androidndk_HelloWorld
#define _Included_com_ruanyandong_androidndk_HelloWorld
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_ruanyandong_androidndk_HelloWorld
 * Method:    getHelloWorld
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_ruanyandong_androidndk_HelloWorld_getHelloWorld
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
